name: RSK
description: RSK is de app van karateschool René Smaal Karate. In de app kan jij jouw lidmaatschap beheren, inchecken voor lessen, inschrijven voor alle toernooien en examens. Ook vind je veel foto's, video's en nieuwsberichten.
#full_description: 'A more complete description of the mobile app<br>
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android: https://play.google.com/store/apps/details?id=app.renesmaal&hl=en_AU&gl=NL
iOS: https://apps.apple.com/bs/app/rsk/id1506214029
#web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.jpg
  - 2.jpg
  - 3.jpg
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
